### PR TITLE
Add cake task for nuspec NHibernate version transformation

### PR DESCRIPTION
**Pull request by michalkowal**
Fix for issue #409 

I added new cake task "Update-Nuspec_Files".
This task change version in all projects nuspecs (normal and symbol).
The result of task - nuspec xml file contains version node, based on semversion.

I also made task "Package" dependant off this new task

### CODE REVIEW

**Comment by jrgcubano** [comment]
Great job @michalkowal. 

It was not the intent of the issue, but the idea is good. The nuspec version is actually updated when packing nuget.

```
   NuGetPack($"{nuspecDir}/{project}.symbols.nuspec", new NuGetPackSettings {
            Version = semVersion,
            ...
        });
```

The issue was to update the version of NHibernate in the nuspec by means of cake, although now I think that overexertion does not make much sense. Sorry for that!
....

Apart of this, other idea is to keep just one version of NHibernate in shared.msbuild and reference that one from any project! 

We can add othe project section in shared.build like this
```
...
<Project>
    <PropertyGroup Label="Package Versions">
        <NHibernatePackageVersion>5.1.1</NHibernatePackageVersion>
    </PropertyGroup>
</Project>
```

and then in the projects (csproj) reference the version.

```
...
  <ItemGroup>
    <PackageReference Include="NHibernate" Version="$(NHibernatePackageVersion)" />
  </ItemGroup>
...
```

What you think? You can go for this if you like.

**Comment by michalkowal** [comment]
What about a version provided right now by GitVersion? Maybe, first off all, set Shared.msbuild version from cake and then build and pack?

**Comment by jrgcubano** [comment]
I think we should update the nhibernate versión manually in shared.msbuild and pick it up from there for the nuspec.

The version of the project will be followed by gitversion as before.

Thanks!

**Comment by michalkowal** [comment]
Ok, finally have it. My fault.
Misunderstanding about NHibernate and FluentNHibernate versions...

**Comment by michalkowal** [comment]
@jrgcubano
Please take a look on latest changes.
For me it looks really promising 🙂

**Comment by jrgcubano** [comment]
Great job @michalkowal! 🥇

**Pull request merged**
